# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: 'Setup Virtual Environment'
description: 'Create a Python virtual environment using uv for fast, reliable installs'

inputs:
  venv-name:
    description: 'Name for the virtual environment directory (will be created in workspace)'
    required: false
    default: '.venv'
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  requirements-file:
    description: 'Optional requirements file to install'
    required: false
    default: ''
  install-package:
    description: 'Optional package specification to install (e.g., ".[dev]" or "package-name")'
    required: false
    default: ''
  extra-index-url:
    description: 'Optional extra index URL for pip'
    required: false
    default: ''

outputs:
  venv-path:
    description: 'Full path to the venv directory'
    value: ${{ steps.create-venv-windows.outputs.venv-path || steps.create-venv-linux.outputs.venv-path }}
  python-path:
    description: 'Path to the Python executable in the venv'
    value: ${{ steps.create-venv-windows.outputs.python-path || steps.create-venv-linux.outputs.python-path }}

runs:
  using: "composite"
  steps:
    # Install uv on Windows
    - name: Install uv (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        Write-Host "Installing uv package manager..."
        irm https://astral.sh/uv/install.ps1 | iex
        # Add to PATH for this job
        "$env:USERPROFILE\.local\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        # Also add to current session
        $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"
        Write-Host "uv installed successfully"

    # Install uv on Linux/macOS
    - name: Install uv (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        echo "Installing uv package manager..."
        curl -LsSf https://astral.sh/uv/install.sh | sh
        # Add to PATH for this job
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        # Also add to current session
        export PATH="$HOME/.local/bin:$PATH"
        echo "uv installed successfully"

    # Create venv and install packages (Windows)
    - name: Create virtual environment (Windows)
      id: create-venv-windows
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        $VENV_NAME = "${{ inputs.venv-name }}"
        $VENV_PATH = "$env:GITHUB_WORKSPACE\$VENV_NAME"
        $PYTHON_VERSION = "${{ inputs.python-version }}"

        # Ensure uv is in PATH
        $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"

        Write-Host "Creating virtual environment at $VENV_PATH with Python $PYTHON_VERSION..."

        # Remove existing venv if present
        if (Test-Path $VENV_PATH) {
          Write-Host "Removing existing venv..."
          Remove-Item -Recurse -Force $VENV_PATH
        }

        # Create venv with uv (will download Python if needed)
        uv venv $VENV_PATH --python $PYTHON_VERSION
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

        $PYTHON_PATH = "$VENV_PATH\Scripts\python.exe"

        # Add venv to PATH
        "$VENV_PATH\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        "venv-path=$VENV_PATH" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
        "python-path=$PYTHON_PATH" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

        Write-Host "Virtual environment created successfully!"
        & $PYTHON_PATH --version

    # Create venv and install packages (Linux/macOS)
    - name: Create virtual environment (Linux/macOS)
      id: create-venv-linux
      if: runner.os != 'Windows'
      shell: bash
      run: |
        VENV_NAME="${{ inputs.venv-name }}"
        VENV_PATH="$GITHUB_WORKSPACE/$VENV_NAME"
        PYTHON_VERSION="${{ inputs.python-version }}"

        # Ensure uv is in PATH
        export PATH="$HOME/.local/bin:$PATH"

        echo "Creating virtual environment at $VENV_PATH with Python $PYTHON_VERSION..."

        # Remove existing venv if present
        if [ -d "$VENV_PATH" ]; then
          echo "Removing existing venv..."
          rm -rf "$VENV_PATH"
        fi

        # Create venv with uv (will download Python if needed)
        uv venv "$VENV_PATH" --python "$PYTHON_VERSION"

        PYTHON_PATH="$VENV_PATH/bin/python"

        # Add venv to PATH
        echo "$VENV_PATH/bin" >> $GITHUB_PATH

        echo "venv-path=$VENV_PATH" >> $GITHUB_OUTPUT
        echo "python-path=$PYTHON_PATH" >> $GITHUB_OUTPUT

        echo "Virtual environment created successfully!"
        "$PYTHON_PATH" --version

    # Install requirements file (Windows)
    - name: Install requirements file (Windows)
      if: inputs.requirements-file != '' && runner.os == 'Windows'
      shell: powershell
      run: |
        $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"
        $VENV_PATH = "${{ steps.create-venv-windows.outputs.venv-path }}"

        Write-Host "Installing requirements from ${{ inputs.requirements-file }} using uv..."
        uv pip install -r "${{ inputs.requirements-file }}" --python "$VENV_PATH\Scripts\python.exe"

    # Install requirements file (Linux/macOS)
    - name: Install requirements file (Linux/macOS)
      if: inputs.requirements-file != '' && runner.os != 'Windows'
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        VENV_PATH="${{ steps.create-venv-linux.outputs.venv-path }}"

        echo "Installing requirements from ${{ inputs.requirements-file }} using uv..."
        uv pip install -r "${{ inputs.requirements-file }}" --python "$VENV_PATH/bin/python"

    # Install package (Windows)
    - name: Install package (Windows)
      if: inputs.install-package != '' && runner.os == 'Windows'
      shell: powershell
      run: |
        $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"
        $VENV_PATH = "${{ steps.create-venv-windows.outputs.venv-path }}"

        $EXTRA_INDEX = ""
        if ("${{ inputs.extra-index-url }}" -ne "") {
          $EXTRA_INDEX = "--extra-index-url ${{ inputs.extra-index-url }}"
        }

        Write-Host "Installing package: ${{ inputs.install-package }} using uv..."
        $cmd = "uv pip install ${{ inputs.install-package }} --python `"$VENV_PATH\Scripts\python.exe`" $EXTRA_INDEX"
        Invoke-Expression $cmd

    # Install package (Linux/macOS)
    - name: Install package (Linux/macOS)
      if: inputs.install-package != '' && runner.os != 'Windows'
      shell: bash
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        VENV_PATH="${{ steps.create-venv-linux.outputs.venv-path }}"

        EXTRA_INDEX=""
        if [ -n "${{ inputs.extra-index-url }}" ]; then
          EXTRA_INDEX="--extra-index-url ${{ inputs.extra-index-url }}"
        fi

        echo "Installing package: ${{ inputs.install-package }} using uv..."
        uv pip install ${{ inputs.install-package }} --python "$VENV_PATH/bin/python" $EXTRA_INDEX
