# Copyright(C) 2024-2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

name: 'Install Lemonade Server'
description: 'Downloads and installs Lemonade Server with hybrid extras'

runs:
  using: 'composite'
  steps:
    - name: Get Lemonade Version
      shell: powershell
      run: |
        $lemonadeVersion = python -c "import sys; sys.path.append('src'); from gaia.version import LEMONADE_VERSION; print(LEMONADE_VERSION)"
        echo "LEMONADE_VERSION=$lemonadeVersion" >> $env:GITHUB_ENV
        Write-Host "Using Lemonade version: $lemonadeVersion"

    - name: Install Lemonade Server
      shell: powershell
      run: |
        Write-Host "=== Installing Lemonade Server ==="

        # Add exclusions for the installer and common install directories
        Add-MpPreference -ExclusionPath "C:\temp\lemonade-server-minimal.msi"
        Add-MpPreference -ExclusionPath "$env:LOCALAPPDATA\Programs\lemonade-server"
        Add-MpPreference -ExclusionPath "$env:ProgramFiles\lemonade-server"
        Add-MpPreference -ExclusionProcess "msiexec.exe"
        Add-MpPreference -ExclusionProcess "lemonade-server.exe"

        # Download and run installer
        $installerPath = "C:\temp\lemonade-server-minimal.msi"

        # Remove existing file if it exists
        if (Test-Path $installerPath) {
          Write-Host "Removing existing installer file"
          Remove-Item $installerPath -Force
        }

        Invoke-WebRequest -Uri "https://github.com/lemonade-sdk/lemonade/releases/download/v$env:LEMONADE_VERSION/lemonade-server-minimal.msi" -OutFile $installerPath -UseBasicParsing

        # Check downloaded file
        if (Test-Path $installerPath) {
          $fileInfo = Get-Item $installerPath
          Write-Host "Downloaded installer: $($fileInfo.Length) bytes"

          # Basic sanity check - installer should be at least 100KB
          if ($fileInfo.Length -lt 100000) {
            Write-Host "ERROR: Downloaded file is suspiciously small ($($fileInfo.Length) bytes)"
            Write-Host "This suggests we downloaded an error page instead of the installer"

            # Check if we got HTML error page (without -Raw and -TotalCount together)
            $firstBytes = Get-Content $installerPath -Encoding Byte -TotalCount 200
            $firstText = [System.Text.Encoding]::ASCII.GetString($firstBytes)
            Write-Host "First 200 characters of downloaded file:"
            Write-Host $firstText
            exit 1
          }
        } else {
          Write-Host "ERROR: Installer file not found after download"
          exit 1
        }

    - name: Run Lemonade Installer
      shell: powershell
      run: |
        Write-Host "Installing Lemonade Server..."
        cd C:\temp
        # Install with default options - the MSI will add lemonade-server to PATH
        Start-Process -FilePath "msiexec.exe" -ArgumentList "/i lemonade-server-minimal.msi /qn EXTRAS=hybrid" -Wait
        Write-Host "Installer completed"

    - name: Verify Installation
      shell: powershell
      run: |
        # Remove exclusions after installation
        Remove-MpPreference -ExclusionPath "C:\temp\lemonade-server-minimal.msi"
        Remove-MpPreference -ExclusionProcess "msiexec.exe"

        # Refresh PATH to pick up newly installed lemonade-server
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")

        # Test lemonade-server command (v9.x C++ server adds itself to PATH)
        $lemonadeCmd = Get-Command lemonade-server -ErrorAction SilentlyContinue
        if ($lemonadeCmd) {
            Write-Host "Found lemonade-server at: $($lemonadeCmd.Source)"
            & lemonade-server --version
            Write-Host "Lemonade Server installed successfully"
        } else {
            Write-Host "lemonade-server not found in PATH"
            Write-Host "Checking common installation locations..."

            # Check common installation paths for the C++ server
            $possiblePaths = @(
                "$env:LOCALAPPDATA\Programs\lemonade-server\lemonade-server.exe",
                "$env:ProgramFiles\lemonade-server\lemonade-server.exe",
                "C:\Program Files\lemonade-server\lemonade-server.exe"
            )

            $found = $false
            foreach ($path in $possiblePaths) {
                if (Test-Path $path) {
                    Write-Host "Found lemonade-server at: $path"
                    & $path --version
                    Write-Host "Lemonade Server installed successfully"
                    $found = $true
                    break
                }
            }

            if (-not $found) {
                Write-Host "ERROR: Could not find lemonade-server executable"
                Write-Host "Please check Lemonade installation documentation for v9.x"
                exit 1
            }
        }